config/routes.rb
Rails.application.routes.draw do

  mathjax 'mathjax'

  resources :functions

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :welcome

end

app/models/function.rb
class Function < ActiveRecord::Base

  def parser(z)


  eval(self.name.gsub(/x/,"#{z}"))
  end

  


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :functions, dependent: :nullify
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController

  def index
    @functions=Function.all
  end

  def new
    @function=Function.new()
  end

  def create
    function_params=params.require(:function).permit(:name)
    @function=Function.new(function_params)

    if @function.save
      flash[:notice]= "function saved"
      redirect_to function_path(@function)
    else
      #validations
      flash[:alert]= ""
    end

  end

  def show
    @model_function=Function.find params[:id]
    @func=MathFunctions::Servicefunction.new(-50,50, @model_function.name)

    def a_transformed
      params['a']=="" ? 1: params['a'].to_f
    end

    def b_transformed
      params['b']=="" ? 1: params['b'].to_f
    end

    def h_transformed
      params['h']=="" ? 0: params['h'].to_f
    end

    def k_transformed
      params['k']=="" ? 0: params['k'].to_f
    end

    respond_to do |format|
      format.html {render}
      format.json {render json: [@func.x_vals, @func.y_vals(a=a_transformed,
        b=b_transformed,
        h=h_transformed,
        k=k_transformed
        )
        ]}
    end
  end

  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user=User.find_by_username params[:username]


    if user.authenticate(params[:password]) && user!=nil

      session[:user_id]=user.id
      redirect_to functions_path, notice: "Signed in!"
    else
      redirect_to functions_path, notice: "Wrong credentials!"
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to functions_path, notice: "Signed out!"

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sin_functions_helper.rb
module SinFunctionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/functions/index.html.erb
<h1>All Functions</h1>

<% @functions.each do |f| %>
  <div>
    <hr>
    <%= link_to f.name, function_path(f) %>
  </div>
<% end %>

app/views/functions/new.html.erb
<%=simple_form_for @function, :url => {:action => "create"} do |f| %>
  <p>
    <p>
      <p>
  <%= f.input :name, class:"form-control", placeholder: "Use Ruby syntax" %>
  <p>
    <p>
      <p>
        <p>
  <%=f.submit({class: "btn btn-primary"})%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<script src="https://use.fontawesome.com/d11f5f62a2.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-79725629-1', 'auto');
  ga('send', 'pageview');

</script>
  <nav class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <!-- logo and company name -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
            <div class="navbar-collapse collapse">


          <a class="navbar-right" href="#">
            <!-- <span class="glyphicon glyphicon-fire logo"> -->
            <!--img class="logo-image" src="images/logo.png"-->
            <i class="fa fa-line-chart fa-2x" aria-hidden="true" style="color:DarkGray;position: absolute;
    top: 8px;
    right: 16px;
    "></i>
          </a>
          <h2  class="navbar-left company-name">Graph transformations</h2>
          <!-- navigation items -->
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "All Functions", functions_path%></li>
            <li><%= link_to "About", welcome_index_path%></li>
            <% if user_signed_in? %>
            <li><%= link_to "Create New Function", new_function_path%></li>
            <li><%= link_to "Log out", sessions_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Admin", new_session_path %></li>

            <% end %>
          </ul>
        </div>
      </nav>
</head>
<body bgcolor="#F5F5F5" >





<%= mathjax_tag %>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
In British Columbia there exists a course called Pre-Calculus 12.<br>
A significant part of Pre-Calculus 12 consists of transforming graphs of functions.<br>
This application is meant to be used as a tool for mastering that part of the material by emphasizing the connection between algebra, geometry and natural language.     <br>

<br>
Being able to transform graphs of functions is useful when it comes to modeling relationships between phenomenon in nature.
<br>
<br>
<br>
<br>
This application is deployed on Heroku. As a consequence, it can sometimes take a couple of minutes before the transformations start to work if the application have not been visited for a while.

<br>
contact: gurbraj.kang@gmail.com